# Generated by Django 5.1.4 on 2025-01-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(verbose_name=30)),
                ('city_name', models.CharField(verbose_name=20)),
                ('state', models.CharField(verbose_name=2)),
                ('zip_code', models.CharField(verbose_name=10)),
                ('country', models.CharField(verbose_name=28)),
                ('country_abbrev', models.CharField(verbose_name=3)),
            ],
        ),
    ]
