# Generated by Django 5.1.4 on 2025-01-09 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comapany',
            new_name='Company',
        ),
    ]
